### ISSUE TITLE
macmodelshelf.db duplicates

### ISSUE THREAD

**Issue by sebnash** [MagerValp/MacModelShelf#1]
More of a question really. I've been using `macmodelshelf.py` at the command line, but each time `macmodelshelf.db` is created in my working directory. Any way around this?

**Comment by MagerValp** [comment]
That's because it caches lookups to avoid hitting Apple's servers for known models. You can initialize it to a plain dict() instead of shelve.open() to avoid it, but I recommend just running it from the same directory.
